# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c5972bbfe5730d1b9ee10d4b21fa2481e47717ff1f9f2538d9f204b8e8428969cd1a536c4d4bf4cb856be965956814f6209265b777f778c803868a35c4026e0

test:
  secret_key_base: 01a0bac0b540c83cfa4b487e6fd0b0167884c49528249245f05d29886feb5e98e3f62558179b651ed2ce1fd9389d421c8f1c0a5f0e857d7c5393bf7dc985b5b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
